version: '3.8'

services:
  redmine:
    build:
      context: ../local/docker
      dockerfile: redmine.Dockerfile
    container_name: redmine
    ports:
      - "3100:3000"
    environment:
      REDMINE_DB_POSTGRES: redmine_db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redminepassword
    volumes:
      - redmine_data:/usr/src/redmine/files
    networks:
      - redmine_network

  redmine_db:
    image: postgres:15
    container_name: redmine-db
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: redminepassword
    volumes:
      - redmine_db_data:/var/lib/postgresql/data
    networks:
      - redmine_network

volumes:
  redmine_data:
  redmine_db_data:

networks:
  redmine_network:
    driver: bridge